/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalFooter: typeof import('./components/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./components/GlobalHeader.vue')['default']
    KoishiPlaceholder: typeof import('./components/KoishiPlaceholder.vue')['default']
    QEmojiMiniCard: typeof import('./components/QEmojiMiniCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
