/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    ':fallback(.*)': RouteRecordInfo<':fallback(.*)', '/:fallback(.*)', { fallback: ParamValue<true> }, { fallback: ParamValue<false> }>,
    'qqnt': RouteRecordInfo<'qqnt', '/qqnt', Record<never, never>, Record<never, never>>,
    'qqnt-:id': RouteRecordInfo<'qqnt-:id', '/qqnt/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'shadcn-playground': RouteRecordInfo<'shadcn-playground', '/shadcn-playground', Record<never, never>, Record<never, never>>,
    'wechat': RouteRecordInfo<'wechat', '/wechat', Record<never, never>, Record<never, never>>,
  }
}
